name: Keep Green

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:     

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Last updated on $(date)" > keepgreen.txt

      - name: Commit changes
        run: |
          git config --global user.name 'janidu622'
          git config --global user.email 'janussiriwardhana@gmail.com'
          git add keepgreen.txt
          git commit -m "Daily commit" || echo "No changes to commit"
          git push
